# ==========================================
# إعدادات البناء المستقرة للهاتف (AndroidIDE)
# ==========================================

# 1. تخصيص الذاكرة (512 ميجا هي النقطة الذهبية لتجنب الانهيار)
org.gradle.jvmargs=-Xmx512m -Dfile.encoding=UTF-8

# 2. إيقاف عمل المترجم في الخلفية لكي لا يقتله نظام الأندرويد
org.gradle.daemon=false

# 3. إيقاف تعدد المهام لتخفيف الضغط على المعالج
org.gradle.parallel=false
org.gradle.workers.max=1

# 4. إعدادات بيئة الأندرويد الحديثة
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# 5. مسار أداة البناء (AAPT2) الخاص بتطبيق AndroidIDE (مهم جداً لا تحذفه)
android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2


